.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. aphory_qt test_aphory_qt
clean: FORCE
	$(MAKE) -C .. aphory_qt_clean test_aphory_qt_clean
check: FORCE
	$(MAKE) -C .. test_aphory_qt_check
bitcoin-qt bitcoin-qt.exe: FORCE
	 $(MAKE) -C .. aphory_qt
