// Copyright (c) 2017-2019 The Aphory Core developers
// Copyright (c) 2019 The Aphory Core developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or http://www.opensource.org/licenses/mit-license.php.
#ifndef APHORY_CHAINPARAMSSEEDS_H
#define APHORY_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the aphory network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0xc1,0x1d,0x38,0x15}, 8250} /* 193.29.56.21 */
};

static SeedSpec6 pnSeed6_test[] = {

};
#endif // APHORY_CHAINPARAMSSEEDS_H
